ALTER TABLE IF EXISTS rawstocks
  ALTER COLUMN token DROP NOT NULL;

ALTER TABLE IF EXISTS stock_master
  ALTER COLUMN token DROP NOT NULL;

ALTER TABLE IF EXISTS active_stock
  ALTER COLUMN token DROP NOT NULL;
