CREATE TABLE IF NOT EXISTS stock_fundamental_profit_loss_periods (
  id BIGSERIAL PRIMARY KEY,
  master_id BIGINT NOT NULL REFERENCES stock_master(id) ON DELETE CASCADE,
  active_stock_id BIGINT NULL REFERENCES active_stock(id) ON DELETE SET NULL,
  snapshot_id BIGINT NULL,
  period TEXT NOT NULL,
  period_numeric TEXT NOT NULL,
  sales NUMERIC NULL,
  revenue NUMERIC NULL,
  financing_profit NUMERIC NULL,
  financing_margin_percent NUMERIC NULL,
  expenses NUMERIC NULL,
  operating_profit NUMERIC NULL,
  opm_percent NUMERIC NULL,
  other_income NUMERIC NULL,
  interest NUMERIC NULL,
  depreciation NUMERIC NULL,
  profit_before_tax NUMERIC NULL,
  tax_percent NUMERIC NULL,
  net_profit NUMERIC NULL,
  eps NUMERIC NULL,
  dividend_payout_percent NUMERIC NULL,
  sales_yoy_growth_percent NUMERIC NULL,
  expenses_manufacturing_cost_percent NUMERIC NULL,
  expenses_material_cost_percent NUMERIC NULL,
  expenses_employee_cost_percent NUMERIC NULL,
  expenses_other_cost_percent NUMERIC NULL,
  other_income_normal NUMERIC NULL,
  net_profit_profit_from_associates NUMERIC NULL,
  net_profit_minority_share NUMERIC NULL,
  net_profit_profit_excl_excep NUMERIC NULL,
  net_profit_exceptional_items NUMERIC NULL,
  net_profit_exceptional_items_at NUMERIC NULL,
  net_profit_profit_for_eps NUMERIC NULL,
  net_profit_profit_for_pe NUMERIC NULL,
  net_profit_yoy_profit_growth_percent NUMERIC NULL,
  last_updated_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (master_id, period_numeric)
);

CREATE INDEX IF NOT EXISTS idx_stock_fundamental_profit_loss_periods_master_period
  ON stock_fundamental_profit_loss_periods (master_id, period_numeric);

CREATE TABLE IF NOT EXISTS stock_fundamental_balance_sheet_periods (
  id BIGSERIAL PRIMARY KEY,
  master_id BIGINT NOT NULL REFERENCES stock_master(id) ON DELETE CASCADE,
  active_stock_id BIGINT NULL REFERENCES active_stock(id) ON DELETE SET NULL,
  snapshot_id BIGINT NULL,
  period TEXT NOT NULL,
  period_numeric TEXT NOT NULL,
  equity_capital NUMERIC NULL,
  reserves NUMERIC NULL,
  borrowing NUMERIC NULL,
  deposits NUMERIC NULL,
  borrowings NUMERIC NULL,
  long_term_borrowings NUMERIC NULL,
  short_term_borrowings NUMERIC NULL,
  other_borrowings NUMERIC NULL,
  other_liabilities NUMERIC NULL,
  advance_from_customers NUMERIC NULL,
  lease_liabilities NUMERIC NULL,
  trade_payables NUMERIC NULL,
  other_liability_items NUMERIC NULL,
  non_controlling_int NUMERIC NULL,
  total_liabilities NUMERIC NULL,
  fixed_assets NUMERIC NULL,
  gross_block NUMERIC NULL,
  accumulated_depreciation NUMERIC NULL,
  building NUMERIC NULL,
  land NUMERIC NULL,
  plant_machinery NUMERIC NULL,
  railway_sidings NUMERIC NULL,
  vehicles NUMERIC NULL,
  computers NUMERIC NULL,
  furniture_n_fittings NUMERIC NULL,
  equipments NUMERIC NULL,
  other_fixed_assets NUMERIC NULL,
  intangible_assets NUMERIC NULL,
  cwip NUMERIC NULL,
  investments NUMERIC NULL,
  other_assets NUMERIC NULL,
  inventories NUMERIC NULL,
  trade_receivables NUMERIC NULL,
  cash_equivalents NUMERIC NULL,
  loans_n_advances NUMERIC NULL,
  other_asset_items NUMERIC NULL,
  total_assets NUMERIC NULL,
  last_updated_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (master_id, period_numeric)
);

CREATE INDEX IF NOT EXISTS idx_stock_fundamental_balance_sheet_periods_master_period
  ON stock_fundamental_balance_sheet_periods (master_id, period_numeric);

CREATE TABLE IF NOT EXISTS stock_fundamental_cash_flow_periods (
  id BIGSERIAL PRIMARY KEY,
  master_id BIGINT NOT NULL REFERENCES stock_master(id) ON DELETE CASCADE,
  active_stock_id BIGINT NULL REFERENCES active_stock(id) ON DELETE SET NULL,
  snapshot_id BIGINT NULL,
  period TEXT NOT NULL,
  period_numeric TEXT NOT NULL,
  cash_from_operating_activity NUMERIC NULL,
  profit_from_operations NUMERIC NULL,
  working_capital_changes NUMERIC NULL,
  receivables NUMERIC NULL,
  inventory NUMERIC NULL,
  payables NUMERIC NULL,
  other_wc_items NUMERIC NULL,
  direct_taxes NUMERIC NULL,
  interest_received NUMERIC NULL,
  dividends_received NUMERIC NULL,
  exceptional_cf_items NUMERIC NULL,
  operating_investments NUMERIC NULL,
  operating_borrowings NUMERIC NULL,
  operating_deposits NUMERIC NULL,
  cash_from_investing_activity NUMERIC NULL,
  investments_purchased NUMERIC NULL,
  investments_sold NUMERIC NULL,
  fixed_assets_purchased NUMERIC NULL,
  fixed_assets_sold NUMERIC NULL,
  acquisition_of_companies NUMERIC NULL,
  invest_in_subsidiaries NUMERIC NULL,
  investment_in_group_cos NUMERIC NULL,
  loans_advances NUMERIC NULL,
  other_investing_items NUMERIC NULL,
  cash_from_financing_activity NUMERIC NULL,
  proceeds_from_shares NUMERIC NULL,
  proceeds_from_borrowings NUMERIC NULL,
  repayment_of_borrowings NUMERIC NULL,
  interest_paid_fin NUMERIC NULL,
  dividends_paid NUMERIC NULL,
  financial_liabilities NUMERIC NULL,
  share_application_money NUMERIC NULL,
  other_financing_items NUMERIC NULL,
  net_cash_flow NUMERIC NULL,
  last_updated_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (master_id, period_numeric)
);

CREATE INDEX IF NOT EXISTS idx_stock_fundamental_cash_flow_periods_master_period
  ON stock_fundamental_cash_flow_periods (master_id, period_numeric);

CREATE TABLE IF NOT EXISTS stock_fundamental_ratios_periods (
  id BIGSERIAL PRIMARY KEY,
  master_id BIGINT NOT NULL REFERENCES stock_master(id) ON DELETE CASCADE,
  active_stock_id BIGINT NULL REFERENCES active_stock(id) ON DELETE SET NULL,
  snapshot_id BIGINT NULL,
  period TEXT NOT NULL,
  period_numeric TEXT NOT NULL,
  debtor_days NUMERIC NULL,
  inventory_days NUMERIC NULL,
  days_payable NUMERIC NULL,
  cash_conversion_cycle NUMERIC NULL,
  working_capital_days NUMERIC NULL,
  roce_percent NUMERIC NULL,
  roe_percent NUMERIC NULL,
  last_updated_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (master_id, period_numeric)
);

CREATE INDEX IF NOT EXISTS idx_stock_fundamental_ratios_periods_master_period
  ON stock_fundamental_ratios_periods (master_id, period_numeric);

CREATE TABLE IF NOT EXISTS stock_fundamental_shareholding_periods (
  id BIGSERIAL PRIMARY KEY,
  master_id BIGINT NOT NULL REFERENCES stock_master(id) ON DELETE CASCADE,
  active_stock_id BIGINT NULL REFERENCES active_stock(id) ON DELETE SET NULL,
  snapshot_id BIGINT NULL,
  period TEXT NOT NULL,
  period_numeric TEXT NOT NULL,
  promoters NUMERIC NULL,
  fiis NUMERIC NULL,
  diis NUMERIC NULL,
  public NUMERIC NULL,
  government NUMERIC NULL,
  others NUMERIC NULL,
  no_of_shareholders NUMERIC NULL,
  last_updated_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (master_id, period_numeric)
);

CREATE INDEX IF NOT EXISTS idx_stock_fundamental_shareholding_periods_master_period
  ON stock_fundamental_shareholding_periods (master_id, period_numeric);
