const firstNonEmpty = (...values) => values.find(value => value !== null && value !== undefined && String(value).trim() !== '') ?? null

const normalizeField = (key, label, aliases = [], sourceAliases = []) => ({
  key,
  label,
  aliases,
  sourceAliases,
  matchStrategy: 'first_non_empty',
})

const NORMALIZED_FUNDAMENTALS_SCHEMA = {
  overview: {
    table: 'stock_fundamental_overview',
    fields: [
      normalizeField('company_name', 'Company Name', ['Company'], ['company_info.company_name', 'company']),
      normalizeField('about', 'About', [], ['company_info.about']),
      normalizeField('key_points', 'Key Points', [], ['company_info.key_points']),
      normalizeField('market_cap', 'Market Cap', [], ['summary.market_snapshot.market_cap']),
      normalizeField('current_price', 'Current Price', [], ['summary.market_snapshot.current_price']),
      normalizeField('high_low', 'High / Low', ['High/Low'], ['summary.market_snapshot.high_low']),
      normalizeField('stock_pe', 'Stock P/E', ['P/E'], ['summary.market_snapshot.stock_pe', 'summary.market_snapshot.pe_ratio']),
      normalizeField('book_value', 'Book Value', [], ['summary.market_snapshot.book_value']),
      normalizeField('dividend_yield', 'Dividend Yield', [], ['summary.market_snapshot.dividend_yield']),
      normalizeField('roce', 'ROCE', [], ['summary.market_snapshot.roce']),
      normalizeField('roe', 'ROE', [], ['summary.market_snapshot.roe']),
      normalizeField('face_value', 'Face Value', [], ['summary.market_snapshot.face_value']),
    ],
  },
  sections: {
    quarterly_results: {
      table: 'stock_fundamental_quarterly_results',
      rowKeys: [
        normalizeField('sales', 'Sales', ['Revenue'], ['Sales', 'Revenue']),
        normalizeField('revenue', 'Revenue', ['Sales'], ['Revenue', 'Sales']),
        normalizeField('financing_profit', 'Financing Profit', [], ['Financing Profit']),
        normalizeField('financing_margin_percent', 'Financing Margin %', [], ['Financing Margin %']),
        normalizeField('raw_pdf', 'Raw PDF', [], ['Raw PDF']),
        normalizeField('expenses', 'Expenses', [], ['Expenses']),
        normalizeField('operating_profit', 'Operating Profit', [], ['Operating Profit']),
        normalizeField('opm_percent', 'OPM %', [], ['OPM %']),
        normalizeField('other_income', 'Other Income', [], ['Other Income']),
        normalizeField('interest', 'Interest', [], ['Interest']),
        normalizeField('depreciation', 'Depreciation', [], ['Depreciation']),
        normalizeField('profit_before_tax', 'Profit before tax', [], ['Profit before tax']),
        normalizeField('tax_percent', 'Tax %', [], ['Tax %']),
        normalizeField('net_profit', 'Net Profit', [
          'Profit from Associates',
          'Minority share',
          'Exceptional items AT',
          'Profit excl Excep',
          'Profit for EPS',
          'Profit for PE',
          'YOY Profit Growth %',
        ], ['Net Profit']),
        normalizeField('eps', 'EPS in Rs', [], ['EPS in Rs']),
        normalizeField('gross_npa_percent', 'Gross NPA %', [], ['Gross NPA %']),
        normalizeField('net_npa_percent', 'Net NPA %', [], ['Net NPA %']),
      ],
    },
    profit_loss: {
      table: 'stock_fundamental_profit_loss_periods',
      extraFields: [
        normalizeField('csg_10y', '10 Years:', [], ['other_details.profit_loss.compounded_sales_growth.entries.0.value']),
        normalizeField('csg_5y', '5 Years:', [], ['other_details.profit_loss.compounded_sales_growth.entries.1.value']),
        normalizeField('csg_3y', '3 Years:', [], ['other_details.profit_loss.compounded_sales_growth.entries.2.value']),
        normalizeField('csg_ttm', 'TTM:', [], ['other_details.profit_loss.compounded_sales_growth.entries.3.value']),
        normalizeField('cpg_10y', '10 Years:', [], ['other_details.profit_loss.compounded_profit_growth.entries.0.value']),
        normalizeField('cpg_5y', '5 Years:', [], ['other_details.profit_loss.compounded_profit_growth.entries.1.value']),
        normalizeField('cpg_3y', '3 Years:', [], ['other_details.profit_loss.compounded_profit_growth.entries.2.value']),
        normalizeField('cpg_ttm', 'TTM:', [], ['other_details.profit_loss.compounded_profit_growth.entries.3.value']),
        normalizeField('spc_10y', '10 Years:', [], ['other_details.profit_loss.stock_price_cagr.entries.0.value']),
        normalizeField('spc_5y', '5 Years:', [], ['other_details.profit_loss.stock_price_cagr.entries.1.value']),
        normalizeField('spc_3y', '3 Years:', [], ['other_details.profit_loss.stock_price_cagr.entries.2.value']),
        normalizeField('spc_1y', '1 Year:', [], ['other_details.profit_loss.stock_price_cagr.entries.3.value']),
        normalizeField('roe_10y', '10 Years:', [], ['other_details.profit_loss.return_on_equity.entries.0.value']),
        normalizeField('roe_5y', '5 Years:', [], ['other_details.profit_loss.return_on_equity.entries.1.value']),
        normalizeField('roe_3y', '3 Years:', [], ['other_details.profit_loss.return_on_equity.entries.2.value']),
        normalizeField('roe_last_year', 'Last Year:', [], ['other_details.profit_loss.return_on_equity.entries.3.value']),
      ],
      rowKeys: [
        normalizeField('sales', 'Sales', ['Revenue'], ['Sales', 'Revenue']),
        normalizeField('revenue', 'Revenue', ['Sales'], ['Revenue', 'Sales']),
        normalizeField('financing_profit', 'Financing Profit', [], ['Financing Profit']),
        normalizeField('financing_margin_percent', 'Financing Margin %', [], ['Financing Margin %']),
        normalizeField('expenses', 'Expenses', [], ['Expenses']),
        normalizeField('operating_profit', 'Operating Profit', [], ['Operating Profit']),
        normalizeField('opm_percent', 'OPM %', [], ['OPM %']),
        normalizeField('other_income', 'Other Income', [], ['Other Income']),
        normalizeField('interest', 'Interest', [], ['Interest']),
        normalizeField('depreciation', 'Depreciation', [], ['Depreciation']),
        normalizeField('profit_before_tax', 'Profit before tax', [], ['Profit before tax']),
        normalizeField('tax_percent', 'Tax %', [], ['Tax %']),
        normalizeField('net_profit', 'Net Profit', [
          'Profit from Associates',
          'Minority share',
          'Exceptional items',
          'Exceptional items AT',
          'Profit excl Excep',
          'Profit for EPS',
          'Profit for PE',
          'Profit Growth %',
        ], ['Net Profit']),
        normalizeField('eps', 'EPS in Rs', [], ['EPS in Rs']),
        normalizeField('dividend_payout_percent', 'Dividend Payout %', [], ['Dividend Payout %']),
      ],
    },
    balance_sheet: {
      table: 'stock_fundamental_balance_sheet_periods',
      rowKeys: [
        normalizeField('equity_capital', 'Equity Capital', [], ['Equity Capital']),
        normalizeField('reserves', 'Reserves', [], ['Reserves']),
        normalizeField('borrowing', 'Borrowing', ['Borrowings'], ['Borrowing', 'Borrowings']),
        normalizeField('deposits', 'Deposits', [], ['Deposits']),
        normalizeField('borrowings', 'Borrowings', ['Borrowing'], ['Borrowings', 'Borrowing']),
        normalizeField('other_liabilities', 'Other Liabilities', [], ['Other Liabilities']),
        normalizeField('total_liabilities', 'Total Liabilities', [], ['Total Liabilities']),
        normalizeField('fixed_assets', 'Fixed Assets', [], ['Fixed Assets']),
        normalizeField('cwip', 'CWIP', [], ['CWIP']),
        normalizeField('investments', 'Investments', [], ['Investments']),
        normalizeField('other_assets', 'Other Assets', [], ['Other Assets']),
        normalizeField('total_assets', 'Total Assets', [], ['Total Assets']),
      ],
    },
    cash_flow: {
      table: 'stock_fundamental_cash_flow_periods',
      rowKeys: [
        normalizeField('cash_from_operating_activity', 'Cash from Operating Activity', [
          'Profit from operations',
          'Working capital changes',
          'Receivables',
          'Inventory',
          'Payables',
          'Other WC items',
          'Direct taxes',
          'Interest received',
          'Dividends received',
          'Exceptional CF items',
          'Operating investments',
          'Operating borrowings',
          'Operating Deposits',
        ], ['Cash from Operating Activity']),
        normalizeField('cash_from_investing_activity', 'Cash from Investing Activity', [
          'Investments purchased',
          'Investments sold',
          'Fixed assets purchased',
          'Fixed assets sold',
          'Acquisition of companies',
          'Invest in subsidiaries',
          'Investment in group cos',
          'Redemp n Canc of Shares',
          'Loans Advances',
          'Other investing items',
        ], ['Cash from Investing Activity']),
        normalizeField('cash_from_financing_activity', 'Cash from Financing Activity', [
          'Proceeds from shares',
          'Proceeds from borrowings',
          'Repayment of borrowings',
          'Interest paid fin',
          'Dividends paid',
          'Financial liabilities',
          'Share application money',
          'Other financing items',
        ], ['Cash from Financing Activity']),
        normalizeField('net_cash_flow', 'Net Cash Flow', [], ['Net Cash Flow']),
      ],
    },
    ratios: {
      table: 'stock_fundamental_ratios_periods',
      rowKeys: [
        normalizeField('debtor_days', 'Debtor Days', [], ['Debtor Days']),
        normalizeField('inventory_days', 'Inventory Days', [], ['Inventory Days']),
        normalizeField('days_payable', 'Days Payable', [], ['Days Payable']),
        normalizeField('cash_conversion_cycle', 'Cash Conversion Cycle', [], ['Cash Conversion Cycle']),
        normalizeField('working_capital_days', 'Working Capital Days', [], ['Working Capital Days']),
        normalizeField('roce_percent', 'ROCE %', [], ['ROCE %']),
        normalizeField('roe_percent', 'ROE %', [], ['ROE %']),
      ],
    },
    shareholdings: {
      table: 'stock_fundamental_shareholdings_periods',
      rowKeys: [
        normalizeField('promoters', 'Promoters', ['<dynamic_holder_rows>'], ['Promoters']),
        normalizeField('fiis', 'FIIs', ['<dynamic_holder_rows>'], ['FIIs']),
        normalizeField('diis', 'DIIs', ['<dynamic_holder_rows>'], ['DIIs']),
        normalizeField('public', 'Public', ['<dynamic_holder_rows>'], ['Public']),
        normalizeField('others', 'Others', ['<dynamic_holder_rows>'], ['Others']),
        normalizeField('no_of_shareholders', 'No. of Shareholders', [], ['No. of Shareholders']),
      ],
    },
    peers: {
      table: 'stock_fundamental_peers_snapshot',
    },
  },
}

module.exports = {
  firstNonEmpty,
  normalizeField,
  NORMALIZED_FUNDAMENTALS_SCHEMA,
}
