const MarketState = Object.freeze({
  INIT: "INIT",
  IDLE: "IDLE",
  WAITING_FOR_TOKEN: "WAITING_FOR_TOKEN",
  TOKEN_READY: "TOKEN_READY",
  PREPARING: "PREPARING",
  FULL_RUNNING: "FULL_RUNNING",
  FULL_MODE: "FULL_MODE",
  FULL_DONE: "FULL_DONE",
  LTC_RUNNING: "LTC_RUNNING",
  LTC_MODE: "LTC_MODE",
  LTC_WAIT: "LTC_WAIT",
  LTC_DONE: "LTC_DONE",
  MARKET_CLOSED: "MARKET_CLOSED",
  OHLC_WAIT: "OHLC_WAIT",
  OHLC_RUNNING: "OHLC_RUNNING",
  OHLC_MODE: "OHLC_MODE",
  OHLC_DONE: "OHLC_DONE",
  DONE: "DONE",
  PAUSED: "PAUSED",
  ERROR: "ERROR",
});

module.exports = MarketState;
